# Default configuration for backtest sweeps
backtest:
  sell_thresholds: [0.80, 0.83, 0.86, 0.89, 0.92, 0.95, 0.98]
  buy_thresholds: [0.70, 0.73, 0.76, 0.79, 0.82, 0.85]
  sl_percents: [0.15, 0.17, 0.19]
  tp_percents: [0.54, 0.61, 0.68, 0.75]
  seed: 42
  model_path: "ml_model/triangular_rf_model.json"

